### ISSUE TITLE
SOLVED: sudo: unable to create sockets: Socket type not supported (CentOS on WSL)

### ISSUE THREAD

**Issue by ryanerwin** [RoliSoft/WSL-Distribution-Switcher#24] opened 2016-12-04 06:53 UTC
Hello,

@jdmansour pointed out in [Atlas on Windows](https://twiki.cern.ch/twiki/bin/view/Main/AtlasOnWindows) that he was also getting `sudo: unable to create sockets: Socket type not supported`. This was the only reference to `sudo: unable to create sockets: Socket type not supported` that I was able to find.

Since **sudo** works under Ubuntu but fails under CentOS, I thought it must be a CentOS issue rather than a WSL issue.

If you're running as root, you can use `sudo -V` to dump a detailed sudo configuration, along with `./configure` compile time flags. After a lot of trial and error, I was able to get sudo working under CentOS via WSL Distribution Switcher.

First, download the sudo sourcecode from [sudo.ws](https://www.sudo.ws).
Then you'll need to install a boatload of dependancies to get this to build.

```
yum install file make zlib zlib-devel \
gcc vim svn wget make \
sssd sssd-libwbclient-devel \
pam-devel libselinux-devel
```

Then you'll want to configure with:

```
./configure  -v --with-all-insults --with-pam \
--with-nsswitch=no --without-ldap --without-sendmail \
--with-logfac=authpriv --with-logging=syslog \
--with-editor=/bin/vi --with-env-editor \
--with-timeout=15 --with-password-timeout=0 \
--with-passprompt="[sudo] password for %p:" \
--without-lecture --with-tty-tickets \
--disable-root-mailer --enable-admin-flag \
--with-sssd --with-sssd-lib=/usr/lib64 \
--with-selinux --enable-zlib \
--without-fqdn
```

Last, you'll want to edit /etc/sudoers. On the very last line, you'll want to put:
```
me   ALL=(ALL) NOPASSWD: ALL

```

Of course **me** should be your actual username. You'll also want to make sure to include a blank line after this line, as it also seems to be required by **sudo**.  This should fix: `sudo: no tty present and no askpass program specified` errors.

I'm sure that it's not the best solution, but it's a viable way to get sudo working on CentOS under WSL. I wish I could think of a way to include this into the post_install script but it's such a long winded process, building a custom RPM would seem to be the most viable option, but then is WSL-Distribution-Switcher going to want to host packages that handle compatability for certain programs?

**Comment by RoliSoft** [comment] 2016-12-06 09:06
Hi,

Thanks for your write-up. I'll look at it over the weekend and decide how to solve it. The installer script does support running multiple hooks, including filtering by distribution. For example, one can include the sudo compiler in a separate `hook_postinstall_centos_7.sh` script, to only run for `centos:7`.

WSL does not support Unix sockets at this time, so if that is what the CentOS version of sudo is trying to do, it will not work. (It was added in the Insider builds, or is in the process of being added, if I'm not mistaken.)

As for the TTY error, you can just run `sudo -S` to instruct sudo to read the password from stdin, which will work.

**Comment by fpqc** [comment] 2016-12-19 16:42
Yep, the problem is datagram sockets, and they're fixed in the insider builds.

**Comment by lohman** [comment] 2017-07-11 02:34
@ryanerwin thanks for the fix

**Comment by zommuter** [comment] 2017-08-04 06:07
Instead of having the title start with _SOLVED_ you can close the issue, which works better with Github's issue system

**Closed as completed** 2017-08-07 14:31 UTC
